<?php
namespace Kotchasan;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-19 at 08:22:48.
 */
class PasswordTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Password
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Password('1234567890');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * Generated from @assert ($this->object->encode("ทดสอบภาษาไทย")) [==] "ทดสอบภาษาไทย".
     *
     * @covers Kotchasan\Password::decode
     */
    public function testDecode()
    {

        $this->assertEquals(
        "ทดสอบภาษาไทย", $this->object->decode($this->object->encode("ทดสอบภาษาไทย"))
        );
    }

    /**
     * Generated from @assert ($this->object->encode(1234)) [==] 1234.
     *
     * @covers Kotchasan\Password::decode
     */
    public function testDecode2()
    {

        $this->assertEquals(
        1234, $this->object->decode($this->object->encode(1234))
        );
    }
}
